-- Create applications table
CREATE TABLE applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  
  -- Part A
  registeredname TEXT,
  tin TEXT,
  physicaladdress TEXT,
  emailaddress TEXT,
  officetelno TEXT,
  yes_no TEXT,
  inwhichyear TEXT,
  activitiesundertaken TEXT,
  nameofcontactperson TEXT,
  telephonenumber TEXT,
  emailaddresses TEXT,
  physicaladdresses TEXT,
  
  -- Part B
  district TEXT,
  county TEXT,
  subcounty TEXT,
  parish TEXT,
  village TEXT,
  distancefromroadcenter TEXT,
  sizeofland TEXT,
  purposeofland TEXT,
  durationofuse TEXT,
  
  status TEXT DEFAULT 'Pending'
);

-- Optional: Disable Row Level Security to allow anonymous inserts and reads (for testing)
-- In a production environment, you should properly configure RLS policies!
ALTER TABLE applications DISABLE ROW LEVEL SECURITY;
